/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface IntlController {
    'setLanguage': (lang: string) => void;
  }
  interface IntlControllerAttributes extends StencilHTMLAttributes {}

  interface IntlDatetime {}
  interface IntlDatetimeAttributes extends StencilHTMLAttributes {}

  interface IntlDictionary {
    'lang': string;
    'resolvePhrase': (name: string, lang?: string) => Promise<string | false>;
    'src': string;
  }
  interface IntlDictionaryAttributes extends StencilHTMLAttributes {
    'lang'?: string;
    'onIntlLangChange'?: (event: CustomEvent<string>) => void;
    'src'?: string;
  }

  interface IntlNumber {}
  interface IntlNumberAttributes extends StencilHTMLAttributes {}

  interface IntlPhraseGroup {
    'name': string;
  }
  interface IntlPhraseGroupAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface IntlPhrase {
    'lang': string;
    'lazy': boolean;
    'name': string;
    'replace': string | { [key: string]: any };
  }
  interface IntlPhraseAttributes extends StencilHTMLAttributes {
    'lang'?: string;
    'lazy'?: boolean;
    'name'?: string;
    'replace'?: string | { [key: string]: any };
  }

  interface IntlPlural {
    'format': () => void;
    /**
    * The `locale` that will be passed to `Intl.PluralRules`  You may also pass in a comma-separated list of values, providing fallbacks
    */
    'lang': string;
    /**
    * The `localeMatcher` that will be passed to `Intl.PluralRules`   Possible options are `best fit` (default) or `lookup`
    */
    'localeMatcher'?: 'lookup' | 'best fit';
    /**
    * The `type` that will be passed to `Intl.PluralRules`  Possible options are `cardinal` (default) or `ordinal`
    */
    'type'?: 'cardinal' | 'ordinal';
    /**
    * An integer value which will be passed to `Intl.PluralRules`  If omitted, the componenet will automatically look for an integer value in the parent element, like so: ```html <div>   42   <intl-plural locale="en-US" type="ordinal">     <span slot="one">st</span>     <span slot="two">nd</span>     <span slot="few">rd</span>     <span>th</span>   </intl-plural> </div>      ```
    */
    'value': number|string;
  }
  interface IntlPluralAttributes extends StencilHTMLAttributes {
    /**
    * The `locale` that will be passed to `Intl.PluralRules`  You may also pass in a comma-separated list of values, providing fallbacks
    */
    'lang'?: string;
    /**
    * The `localeMatcher` that will be passed to `Intl.PluralRules`   Possible options are `best fit` (default) or `lookup`
    */
    'localeMatcher'?: 'lookup' | 'best fit';
    /**
    * The `type` that will be passed to `Intl.PluralRules`  Possible options are `cardinal` (default) or `ordinal`
    */
    'type'?: 'cardinal' | 'ordinal';
    /**
    * An integer value which will be passed to `Intl.PluralRules`  If omitted, the componenet will automatically look for an integer value in the parent element, like so: ```html <div>   42   <intl-plural locale="en-US" type="ordinal">     <span slot="one">st</span>     <span slot="two">nd</span>     <span slot="few">rd</span>     <span>th</span>   </intl-plural> </div>      ```
    */
    'value'?: number|string;
  }

  interface IntlRelativeTime {}
  interface IntlRelativeTimeAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'IntlController': Components.IntlController;
    'IntlDatetime': Components.IntlDatetime;
    'IntlDictionary': Components.IntlDictionary;
    'IntlNumber': Components.IntlNumber;
    'IntlPhraseGroup': Components.IntlPhraseGroup;
    'IntlPhrase': Components.IntlPhrase;
    'IntlPlural': Components.IntlPlural;
    'IntlRelativeTime': Components.IntlRelativeTime;
  }

  interface StencilIntrinsicElements {
    'intl-controller': Components.IntlControllerAttributes;
    'intl-datetime': Components.IntlDatetimeAttributes;
    'intl-dictionary': Components.IntlDictionaryAttributes;
    'intl-number': Components.IntlNumberAttributes;
    'intl-phrase-group': Components.IntlPhraseGroupAttributes;
    'intl-phrase': Components.IntlPhraseAttributes;
    'intl-plural': Components.IntlPluralAttributes;
    'intl-relative-time': Components.IntlRelativeTimeAttributes;
  }


  interface HTMLIntlControllerElement extends Components.IntlController, HTMLStencilElement {}
  var HTMLIntlControllerElement: {
    prototype: HTMLIntlControllerElement;
    new (): HTMLIntlControllerElement;
  };

  interface HTMLIntlDatetimeElement extends Components.IntlDatetime, HTMLStencilElement {}
  var HTMLIntlDatetimeElement: {
    prototype: HTMLIntlDatetimeElement;
    new (): HTMLIntlDatetimeElement;
  };

  interface HTMLIntlDictionaryElement extends Components.IntlDictionary, HTMLStencilElement {}
  var HTMLIntlDictionaryElement: {
    prototype: HTMLIntlDictionaryElement;
    new (): HTMLIntlDictionaryElement;
  };

  interface HTMLIntlNumberElement extends Components.IntlNumber, HTMLStencilElement {}
  var HTMLIntlNumberElement: {
    prototype: HTMLIntlNumberElement;
    new (): HTMLIntlNumberElement;
  };

  interface HTMLIntlPhraseGroupElement extends Components.IntlPhraseGroup, HTMLStencilElement {}
  var HTMLIntlPhraseGroupElement: {
    prototype: HTMLIntlPhraseGroupElement;
    new (): HTMLIntlPhraseGroupElement;
  };

  interface HTMLIntlPhraseElement extends Components.IntlPhrase, HTMLStencilElement {}
  var HTMLIntlPhraseElement: {
    prototype: HTMLIntlPhraseElement;
    new (): HTMLIntlPhraseElement;
  };

  interface HTMLIntlPluralElement extends Components.IntlPlural, HTMLStencilElement {}
  var HTMLIntlPluralElement: {
    prototype: HTMLIntlPluralElement;
    new (): HTMLIntlPluralElement;
  };

  interface HTMLIntlRelativeTimeElement extends Components.IntlRelativeTime, HTMLStencilElement {}
  var HTMLIntlRelativeTimeElement: {
    prototype: HTMLIntlRelativeTimeElement;
    new (): HTMLIntlRelativeTimeElement;
  };

  interface HTMLElementTagNameMap {
    'intl-controller': HTMLIntlControllerElement
    'intl-datetime': HTMLIntlDatetimeElement
    'intl-dictionary': HTMLIntlDictionaryElement
    'intl-number': HTMLIntlNumberElement
    'intl-phrase-group': HTMLIntlPhraseGroupElement
    'intl-phrase': HTMLIntlPhraseElement
    'intl-plural': HTMLIntlPluralElement
    'intl-relative-time': HTMLIntlRelativeTimeElement
  }

  interface ElementTagNameMap {
    'intl-controller': HTMLIntlControllerElement;
    'intl-datetime': HTMLIntlDatetimeElement;
    'intl-dictionary': HTMLIntlDictionaryElement;
    'intl-number': HTMLIntlNumberElement;
    'intl-phrase-group': HTMLIntlPhraseGroupElement;
    'intl-phrase': HTMLIntlPhraseElement;
    'intl-plural': HTMLIntlPluralElement;
    'intl-relative-time': HTMLIntlRelativeTimeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
