/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface IntlDatetime {}
  interface IntlDatetimeAttributes extends StencilHTMLAttributes {}

  interface IntlNumber {}
  interface IntlNumberAttributes extends StencilHTMLAttributes {}

  interface IntlPlural {
    'format': () => void;
    /**
    * The `locale` that will be passed to `Intl.PluralRules`  You may also pass in a comma-separated list of values, providing fallbacks
    */
    'lang': string;
    /**
    * The `localeMatcher` that will be passed to `Intl.PluralRules`   Possible options are `best fit` (default) or `lookup`
    */
    'localeMatcher'?: 'lookup' | 'best fit';
    /**
    * An integer value which will be passed to `Intl.PluralRules`  If omitted, the componenet will automatically look for an integer value in the parent element, like so: ```html <div>   42   <intl-plural locale="en-US" type="ordinal">     <span slot="one">st</span>     <span slot="two">nd</span>     <span slot="few">rd</span>     <span>th</span>   </intl-plural> </div>      ```
    */
    'number': string;
    /**
    * The `type` that will be passed to `Intl.PluralRules`  Possible options are `cardinal` (default) or `ordinal`
    */
    'type'?: 'cardinal' | 'ordinal';
  }
  interface IntlPluralAttributes extends StencilHTMLAttributes {
    /**
    * The `locale` that will be passed to `Intl.PluralRules`  You may also pass in a comma-separated list of values, providing fallbacks
    */
    'lang'?: string;
    /**
    * The `localeMatcher` that will be passed to `Intl.PluralRules`   Possible options are `best fit` (default) or `lookup`
    */
    'localeMatcher'?: 'lookup' | 'best fit';
    /**
    * An integer value which will be passed to `Intl.PluralRules`  If omitted, the componenet will automatically look for an integer value in the parent element, like so: ```html <div>   42   <intl-plural locale="en-US" type="ordinal">     <span slot="one">st</span>     <span slot="two">nd</span>     <span slot="few">rd</span>     <span>th</span>   </intl-plural> </div>      ```
    */
    'number'?: string;
    /**
    * The `type` that will be passed to `Intl.PluralRules`  Possible options are `cardinal` (default) or `ordinal`
    */
    'type'?: 'cardinal' | 'ordinal';
  }

  interface IntlRelativeTime {}
  interface IntlRelativeTimeAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'IntlDatetime': Components.IntlDatetime;
    'IntlNumber': Components.IntlNumber;
    'IntlPlural': Components.IntlPlural;
    'IntlRelativeTime': Components.IntlRelativeTime;
  }

  interface StencilIntrinsicElements {
    'intl-datetime': Components.IntlDatetimeAttributes;
    'intl-number': Components.IntlNumberAttributes;
    'intl-plural': Components.IntlPluralAttributes;
    'intl-relative-time': Components.IntlRelativeTimeAttributes;
  }


  interface HTMLIntlDatetimeElement extends Components.IntlDatetime, HTMLStencilElement {}
  var HTMLIntlDatetimeElement: {
    prototype: HTMLIntlDatetimeElement;
    new (): HTMLIntlDatetimeElement;
  };

  interface HTMLIntlNumberElement extends Components.IntlNumber, HTMLStencilElement {}
  var HTMLIntlNumberElement: {
    prototype: HTMLIntlNumberElement;
    new (): HTMLIntlNumberElement;
  };

  interface HTMLIntlPluralElement extends Components.IntlPlural, HTMLStencilElement {}
  var HTMLIntlPluralElement: {
    prototype: HTMLIntlPluralElement;
    new (): HTMLIntlPluralElement;
  };

  interface HTMLIntlRelativeTimeElement extends Components.IntlRelativeTime, HTMLStencilElement {}
  var HTMLIntlRelativeTimeElement: {
    prototype: HTMLIntlRelativeTimeElement;
    new (): HTMLIntlRelativeTimeElement;
  };

  interface HTMLElementTagNameMap {
    'intl-datetime': HTMLIntlDatetimeElement
    'intl-number': HTMLIntlNumberElement
    'intl-plural': HTMLIntlPluralElement
    'intl-relative-time': HTMLIntlRelativeTimeElement
  }

  interface ElementTagNameMap {
    'intl-datetime': HTMLIntlDatetimeElement;
    'intl-number': HTMLIntlNumberElement;
    'intl-plural': HTMLIntlPluralElement;
    'intl-relative-time': HTMLIntlRelativeTimeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
